[credentials]
"admin" = "democracy1900"
"debodeep"= "debo123"
"burcu"= "burcu123"
"stefano"= "stefano123"
"andrea"= "andrea123"
"rajib"= "rajib123"
[gcp_service_account]
{
  "type": "service_account",
  "project_id": "gen-lang-client-0527344555",
  "private_key_id": "f5d26acabd05ea443aaff55be6c8aefad068cf00",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDCHcULxPsNsiGr\ndphjUq9ut80ejoXTbcI/Y/AuNunhTmjWmpwDNkgzXzem0chzvgOVjezSabarJHqL\nKSa7QEI2nZ6JDHR0MOeVsWt/RPpFK2CC/5bRZdcDysGZhPnvRiOGHGQlcugrJ4dx\nLmU5FNMNUqyepfhgqv+S6nRkUPLYQ35M78/HYF4h4RdF9JG+1MdzDFJsOW5rPNM7\ndB4oCe6kCZ3AnMpA8YD30O3VQmHmohfZMS/mE9NIo2QRPN+BhdCH4yJXz8cCW8Nb\nSvEcvCvJZeQxalQgYmYVpm5eiGkiZpaQNASbHcW3PvbHtk/91pE4aP69XUOlJTcM\nIm4TyfJpAgMBAAECggEADaCUlxrtzpK7lZOIM/c3pNVdnp0kYyj7z5w7qqlLcF6J\nmM2jav/ojN9/9kOyVGdgGqOrOHcYNJnyMGRj+UlHKX/8A5fOpRZTa6+k4eGWk2+6\nh5FbcrlsVGVrg4eEtEaypiH5tddQ2f0dOQjbLYKuV+t+sTSD/bIdEKDjXH3otN3V\nmngBaUbzXcDiFmsr5l4sHwrReuzEpmb+x110/9PIIErtpbne/BDh/wZ646Bkt26z\nLMfbbcO8LX1nCN+qqAplman5l3NXKFET493tr42LIS/fgv01C9DeCIjR8ffiUx3b\np7c/6251s9iIczP4SFhrNWCsXRD8n/bo0kqdolmccQKBgQDlcutboGFXd5k/ZQFf\nhw19qfXdWC14EC2Vj30emSo9d7s+Ish2CTRAp3kP1prP07TcHnmDeJ+mIGnfjxEc\nQxQO8PZY0yJmZL71aAumeKI0n8Nn7/TupstOFoGyVGnzTuXaJbwdESG+CprcHla3\nh4o8ke1NpuGR9M73x4Ggp3wSXwKBgQDYlCyoEsRGueQkCVfYyupcPFlVMsUTPzao\nuuiOMtHlNK7RAHRoAflGX3OU9q6VsHMesMzZvdkddu0xAdIBC68u6ZxvsuAcngtp\nB2ZgozWjMNthQSbIX2YGg4C9k26Rs/oPev/e19cyxOkKNMSU+PPFy0Iglm4oIdQ4\n+CPPrx4ANwKBgQDCYsOmUo9lLLu2C3pIVgBF8BGNvkB3MS2NQYz8uUIh5SfKkmlG\nJrIP/FIB6wwo+fCFc4P6r9yBP4Cyl2Alk2aQ6e+qfOTt3ngxLD6CgDzbXGaNzaqx\n7LjcpRCn5gAE01jDoahm77aobA+aYFGTFs80VWS3nqQHpWEaZfkaBAqG/QKBgC6j\nkg5LpErawx9jh7Be2iMst8waF8hyR3IEdgoRNZQXSUImx+qR6j1WVsyQZr5Ddjb4\nudR2BqhKsP9ptfCVtI70rcR8D7j569kdR9Wtr+JJpiSGZDSoHo9uiC3K7vefe00U\nHr+9WVFMiCazgFXYWp6Qi9f6rRQlXM872HJj8qD3AoGASwnJiT202vIzY0A3j47L\nPtbSYkAZji562QFtO7V2NF4+muKUGS4SV2JmRiU0HUaBdjuSQZHFrcokHqw7lf0F\n/6XAjbFGeob7sto72gS8FouiQg0H7X9o61dkBYfGLmNvrsRDkuZMlsKjArhfHi02\nUKxgASlu8e83Y/iG6S4+RQA=\n-----END PRIVATE KEY-----\n",
  "client_email": "slog-197@gen-lang-client-0527344555.iam.gserviceaccount.com",
  "client_id": "105858620784130369040",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/slog-197%40gen-lang-client-0527344555.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
