[credentials]
"admin" = "democracy1900"
"debodeep"= "debo123"
"burcu"= "burcu123"
"stefano"= "stefano123"
"andrea"= "andrea123"
"rajib"= "rajib123"
[github]
token = "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"
