[credentials]
"admin" = "democracy1900"
"debodeep"= "debo123"
"burcu"= "burcu123"
"stefano"= "stefano123"
"andrea"= "andrea123"
"rajib"= "rajib123"
[github]
username = "Debodeep94"
token = "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"
repo = "SLOG-Eval"
branch = "main"  # optional
[gist]
id = "208eeccefb34fdcbc877689c2b0c9d0b"
